services:
    web:
        build:
            context: ./web
        depends_on:
            - cms
        networks:
            - mea-custom-network

    cms:
        build:
            context: ./cms
        environment:
            - DATABASE_URI=mongodb://admin:${DB_PASS}@db:27017/mea?authSource=admin
        depends_on:
            - db
        volumes:
            - mea-cms-media:/app/media
        networks:
            - mea-custom-network

    db:
        image: mongo:8.0.1
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
        volumes:
            - mea-db-data:/data/db
        networks:
            - mea-custom-network

    db-client:
        image: mongo-express:1.0.2-20-alpine3.19
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://admin:${DB_PASS}@db:27017/mea?authSource=admin
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: ${DB_CLIENT_PASS}
            ME_CONFIG_SITE_BASEURL: /db-client/
        depends_on:
            - db
        networks:
            - mea-custom-network

networks:
    mea-custom-network:
        external: true

volumes:
    mea-cms-media:
    mea-db-data:
